### ISSUE TITLE
Base image uses Debian Buster, but Mono release for Stretch is installed

### ISSUE THREAD

**Issue by michaelosthege** [jonemo/pythonnet-docker#2]
This line: https://github.com/jonemo/pythonnet-docker/blob/c3dd8429cd0d86d0cef0f1d0d7bf90562473931a/_dockerfiles/python3.7.7-mono5.20-pythonnet2.5.0#L7

I just noticed while investigating a warning during installation of dotnet-sdk-3.1.

**Comment by jonemo** [comment]
I was wondering if I could get away with this. I didn't see any issues during my cursory tests, but it looks like you found the problem...

It looks like there are no Mono 5.x packages available for Buster. Therefore, I should probably downgrade the Mono 5.20 images to Stretch and then create a separate set of images with Buster an 6.x. I have not yet tested PythonNET with Mono 6.x, so that might be another stumbling block.

@michaelosthege Does that plan sound right to you?

**Comment by michaelosthege** [comment]
Sounds right.
As I'm using .NET Core within the image, I'm not sure if I would even encounter potential problems with Mono, but I'll let you know if I do.
